### PR TITLE
Issue#83: fix compatibility issue with go-redis v9.2.0

### PR DESCRIPTION
**Pull request by bertold**
Also, update the dependency to be v9.2.0

### CODE REVIEW

**Review by micronull — APPROVED** [review]

**Comment by ehsannm** [comment]
any ETA ?

**Comment by bertold** [comment]
@ehsannm - I do not have merge privileges.

**Comment by ehsannm** [comment]
Thanks @bertold , until merge will handle by gomod replace to your repo . 👍🏽

**Comment by CodingMinds** [comment]
I'm also waiting for this to be merged 🙂

**Comment by desol** [comment]
Also waiting for this 👍

**Comment by ced42** [comment]
Also waiting for this. Could you please merge it?

**Comment by monkey92t** [comment]
I'm very sorry, I just received the email that Bertold sent to me. I don't know what went wrong with my GitHub subscription; it seems like it didn't notify me...I have simultaneously created a tag for version v9.2.0

**Pull request merged**
